In [1]:
import pandas as pd
import seaborn as sns

In [3]:
t = sns.load_dataset('titanic')
t.head(2)

survived  pclass     sex   age  sibsp  parch     fare embarked  class  \
0         0       3    male  22.0      1      0   7.2500        S  Third   
1         1       1  female  38.0      1      0  71.2833        C  First   

     who  adult_male deck  embark_town alive  alone  
0    man        True  NaN  Southampton    no  False  
1  woman       False    C    Cherbourg   yes  False

In [4]:
t.columns

Index(['survived', 'pclass', 'sex', 'age', 'sibsp', 'parch', 'fare',
       'embarked', 'class', 'who', 'adult_male', 'deck', 'embark_town',
       'alive', 'alone'],
      dtype='object')

In [5]:
# lets prepare data
tf = t.loc[:,['survived','pclass','age','sibsp','fare']]
tf.head()

survived  pclass   age  sibsp     fare
0         0       3  22.0      1   7.2500
1         1       1  38.0      1  71.2833
2         1       3  26.0      0   7.9250
3         1       1  35.0      1  53.1000
4         0       3  35.0      0   8.0500

In [7]:
tf.shape

(891, 5)

In [6]:
tf.isna().sum()

survived      0
pclass        0
age         177
sibsp         0
fare          0
dtype: int64

In [9]:
ag = tf.age.mean()
round(ag,2)

29.7

In [11]:
# handle missing values
# to fill nan value use fillna() from pandas
tf.age.fillna(29.7,inplace=True)

In [12]:
# check after filling NaN value
tf.isna().sum()

survived    0
pclass      0
age         0
sibsp       0
fare        0
dtype: int64

### we have clean data now lets separate input and output

In [14]:
inp = tf.iloc[:,1:]
inp[:2]

pclass   age  sibsp     fare
0       3  22.0      1   7.2500
1       1  38.0      1  71.2833

In [15]:
out = tf.survived
out[:2]

0    0
1    1
Name: survived, dtype: int64

In [17]:
from sklearn.naive_bayes import GaussianNB,BernoulliNB,MultinomialNB

In [18]:
gnb = GaussianNB()
#training
gnb.fit(inp,out)

GaussianNB()

In [21]:
tf[56:57]

survived  pclass   age  sibsp  fare
56         1       2  21.0      0  10.5

In [22]:
# prediction
gnb.predict([[3,56,3,34.88]])

array([0], dtype=int64)

In [23]:
# NB is Porablistic model: check prediction probability
gnb.predict_proba([[3,56,3,34.88]])
# we have 2 prob.
#          [[0,     1]]

array([[0.99700574, 0.00299426]])

In [24]:
0.99700574+0.00299426

1.0

In [29]:
# second case
gnb.predict([[1,24,0,14.5]])

array([1], dtype=int64)

In [30]:
gnb.predict_proba([[1,24,0,14.5]])

array([[0.37192116, 0.62807884]])

In [32]:
#check score  for data
gnb.score(inp,out)*100

68.12570145903479

In [33]:
tf

survived  pclass   age  sibsp     fare
0           0       3  22.0      1   7.2500
1           1       1  38.0      1  71.2833
2           1       3  26.0      0   7.9250
3           1       1  35.0      1  53.1000
4           0       3  35.0      0   8.0500
..        ...     ...   ...    ...      ...
886         0       2  27.0      0  13.0000
887         1       1  19.0      0  30.0000
888         0       3  29.7      1  23.4500
889         1       1  26.0      0  30.0000
890         0       3  32.0      0   7.7500

[891 rows x 5 columns]